before:
  hooks:
    - go mod download
builds:
- id: main
  main: .
  binary: mopsos
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
      - "ghcr.io/adfinis/mopsos:{{ .Tag }}"
      - "ghcr.io/adfinis/mopsos:v{{ .Major }}"
      - "ghcr.io/adfinis/mopsos:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/adfinis/mopsos:latest"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    extra_files:
      - etc/passwd
